### PR TITLE
Handle execvp error in open_browser

### LINKED ISSUE #476: Dunst crashes if browser variable is invalid
No matter what I set the `browser` variable to, Firefox is opened when I open a URL. 

I've tried `browser=xdg-open`, `browser=/usr/bin/xdg-open`, `browser=waterfox`, and `browser=/usr/bin/waterfox`. All of these are ignored.

If I uninstall Firefox, I get the error
```
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 129 requests (129 known processed) with 0 events remaining.
XIO:  fatal IO error 11 (Resource temporarily unavailable) on X server ":0"
      after 141 requests (141 known processed) with 0 events remaining.
```
and dunst crashes.

### Installation info

- Version: `1.3.0`
- Install type: `Package`
- Distro and version: `Arch Linux`

### PR DESCRIPTION
**Pull request by bebehei**
The execvp function usually doesn't return and exits by itself. But,
when having an error, it returns. As a faulty browser setting could
trigger this, dunst has to handle this, as the forked child wants to
access the X11 server too, resulting in XIO errors.

Fixes #476

### CODE REVIEW

File: src/menu.c [hunk 1]
```diff
@@ -119,6 +119,12 @@ void open_browser(const char *in)
                             string_append(settings.browser, url, " ");
                         char **cmd = g_strsplit(browser_cmd, " ", 0);
                         execvp(cmd[0], cmd);
+                        // execvp won't return if it's successful
+                        // so, if we're here, it's definitely an error
+                        fprintf(stderr, "Warning: failed to execute '%s': %s\n",
+                                        settings.browser,
```
Comment (tsipinakis) [inline src/menu.c]: `settings.browser` is being overwritten above by the `string_append` call and can potentially be empty or point to junk here. Perhaps printing `browser_cmd` is better.

Comment (bebehei) [reply src/menu.c]: Albeit not outdated, I've handled this in the `string_append` lines above.

**Comment by bebehei** [comment]
@tsipinakis I've also handled the initial bug for #456.

When the `dmenu` setting is faulty, dunst gets reluctant to signals and it can get only stopped via `SIGKILL`.
