### PR TITLE
Queues tests

### LINKED ISSUE #563: Dunst doesn't respect `-r` (replace) anymore
I have fetched the latest version of Dunst today and built it. It seems that the replace functionality is not working anymore although it was working before perfectly.

``` sh
$ dunstify -r 2593 -p "test volume"
13
$ dunstify -r 2593 -p "test volume"
14
$ dunstify -r 2593 -p "test volume"
15
```
It seems that it no longer replaces the previous id and my volume notifications are stacking up on top of each other. As it's showed in the snippet every time it runs, A new id is generated and doesn't respect the `-r $id` anymore.

**The last working commit** is: `f0b047497eabf3`, so whatever has caused this issue is in the following commit that was merged on `2018-11-11`:
``` sh
d879d70da060ea 2018-10-25 12:32 +0200 Jordan Galby Implement stack_tag, implementing x-canonical-private-synchronous
```
Before this commit the result of the above snippet was as expected:
``` sh
$ dunstify -r 2593 -p "test volume"
2593
$ dunstify -r 2593 -p "test volume"
2593
$ dunstify -r 2593 -p "test volume"
2593
```
### Installation info

- Version: `Dunst - A customizable and lightweight notification-daemon v1.3.2-235-gd786381`
- Install type: `manually`
- Distro and version: ` Ubuntu 18.04.1 LTS x86_64`

### PR DESCRIPTION
**Pull request by bebehei**
---

Edit: Fixes #563

### CODE REVIEW

**Comment by tsipinakis** [comment]
That's a very good catch! We hadn't had a discussion on it but previously we assigned the ID asked anyway. The notification spec doesn't specify what to do if the ID is invalid but we should preserve the previous behaviour to not break those that use a static id replacement as the old workaround for `stack_tag`.

I consider this a bug and it was probably introduced in #552.

**Comment by tsipinakis** [comment]
I pushed a fix @bebehei

File: test/queues.c [hunk 1]
```diff
@@ -529,6 +529,67 @@ TEST test_queues_update_paused(void)
         PASS();
 }
 
+TEST test_queues_update_sicker(void)
```
[the remark this answers is not in the document]
Comment (bebehei) [reply test/queues.c]: `s/sicker/seep/g`.

Sorry, I totally missed that this isn't even an english word :grin:

File: test/queues.c [hunk 2]
```diff
@@ -355,6 +355,65 @@ TEST test_datachange_ttl(void)
...
+        QUEUE_LEN_ALL(0, 1, 0);
+        NOT_LAST(n2);
+
+        ACT_DEINIT();
+        PASS();
+}
+
+TEST test_queue_stacktag(void)
+{
+        const char *stacktag = "THIS IS A SUPER WIERD STACK TAG";
```
[the remark this answers is not in the document]
Comment (bebehei) [reply test/queues.c]: Intended ;-)

File: test/queues.h [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+#define QUEUE(q) QUEUE_##q
+
+#define ACT_INIT() queues_init()
+#define ACT_DEINIT() teardown_queues()
+#define ACT_INS(n) queues_notification_insert(n)
+#define ACT_CLS(n) queues_notification_close(n, REASON_UNDEF)
+#define ACT_CLS_ID(id) queues_notification_close_id(id, REASON_UNDEF)
+#define ACT_RPL(n) queues_notification_replace_id(n)
+#define ACT_RUN(data) queues_update(data)
+#define ACT_REDISPLAY(data) queues_upodate(data)
```
[the remark this answers is not in the document]
Comment (bebehei) [reply test/queues.h]: Full ACK. I first started the tests, I basically packed everything into a macro. In the meantime, I've learnt, that `ASSERTm` does a pretty awesome job in most cases.

But I hadn't been able to remove all the unused (and unnecessary) macros.

**Comment by bebehei** [comment]
Most of the stuff is now fixed.

> I also found a bug: After a notification is shown and closed the dunst window isn't hidden, a small black rectangle keeps being displayed (and moves around the screens with the cursor as would be expected). Bisect showed 052d9f7 as the broken commit.

This is now fixed. The `visible` field of the `dunst_status` structure was absolutely redundant. I tripped too much over the word `visible`, which had different meanings in different contexts.

But shame on me, that I requested your review, but did not even bother to run dunst :face_with_head_bandage:

File: src/queues.c [hunk 4]
```diff
@@ -121,6 +123,36 @@ static bool queues_notification_is_ready(const struct notification *n, struct du
...
+        assert(n);
+
+        if (n->timeout == 0) // sticky
+                return true;
+        if (n->start == 0)   // hidden // TODO: is this really the implication of hidden?
+                return true;
+
+        /* don't timeout when user is idle */
+        if (status.idle && !status.fullscreen && !n->transient) {
+                n->start = time_monotonic_now();
```
Comment (tsipinakis) [inline src/queues.c]: Why are you modifying `n->start` in a query function? What's the point of this if block entirely?

File: src/queues.c [hunk 5]
```diff
@@ -343,68 +375,32 @@ void queues_history_push_all(void)
 }
 
 /* see queues.h */
-void queues_check_timeouts(struct dunst_status status)
+void queues_update(struct dunst_status status)
```
Comment (tsipinakis) [inline src/queues.c]: These are 2 huge and complicated functions, let's break them down rather than merge them.

File: src/notification.c [hunk 6]
```diff
@@ -450,6 +450,7 @@ static void notification_format_message(struct notification *n)
                 case '\0':
                         LOG_W("format_string has trailing %% character. "
                               "To escape it use %%%%.");
+                        substr++;
```
[the remark this answers is not in the document]
Comment (bebehei) [reply src/notification.c]: If I set `substr` to `NULL`, the `substr = strchr(substr, '%')` expression, which will get executed at the end of the loop will segfault.

File: src/queues.c [hunk 7]
```diff
@@ -455,7 +455,7 @@ void queues_update(struct dunst_status status)
                 while (   (i_waiting   = g_queue_peek_head_link(waiting))
                        && (i_displayed = g_queue_peek_tail_link(displayed))) {
 
-                        while (i_waiting && ! queues_notification_is_ready(i_waiting->data, status, true)) {
+                        while (i_waiting && ! queues_notification_is_ready(i_waiting->data, status, false)) {
```
[the remark this answers is not in the document]
Comment (bebehei) [reply src/queues.c]: > From here, the bug and the solution becomes obvious: We can simplify the entire function to
> 
> ```
> return n->fullscreen == FS_SHOW || !fullscreen;
> ```

I'd love to simplify it as that. But it's exactly that corner case you're pointing out. Let's rephrase it in language:

fullscreen, visible = (1,1) means that the notification got inserted and shown while in a "normal" mode, but afterwards you switched a window to fullscreen.

And that's the exact point between delay and pushback:

https://github.com/dunst-project/dunst/blob/d879d70da060ea78fe735d62249a0afdf3e61bc8/dunstrc#L318-L323

File: src/queues.c (hunk 5 above)
Comment (bebehei) [reply src/queues.c]: I don't see any benefit of splitting this method.

There are 4 parts, which are required to be executed in exactly this order and the logics involved is nowhere else necessary.

Additonally, the complex testing logic is already splitted out into `queues_notification_is_(ready|finished)`.

File: src/queues.c [hunk 8]
```diff
@@ -121,6 +123,36 @@ static bool queues_notification_is_ready(const struct notification *n, struct du
                 return true;
 }
 
+/**
+ * Check if a notification has timed out
+ *
+ * @param n the notification to check
+ * @param status the current status of dunst
+ * @returns true, if the notification isn't timed out, otherwise false
```
[the remark this answers is not in the document]
Comment (bebehei) [reply src/queues.c]: Thanks for pointing out such a stupid nobrainer.

File: src/queues.c (hunk 4 above)
Comment (bebehei) [reply src/queues.c]: You're never considered idle, if you're in fullscreen. Current master:

https://github.com/dunst-project/dunst/blob/ed341dfca30ed496bb056a00251af6a17d1f7a07/src/queues.c#L346

I think, I should use exactly this line in there also in the new function.

File: src/queues.c [hunk 9]
```diff
@@ -134,15 +134,15 @@ int queues_notification_insert(struct notification *n)
         }
         /* Do not insert the message if it's a command */
         if (STR_EQ("DUNST_COMMAND_PAUSE", n->summary)) {
-                pause_displayed = true;
+                dunst_status(S_RUNNING, false);
```
[the remark this answers is not in the document]
Comment (tsipinakis) [reply src/queues.c]: I don't think we'd ever need to actively signal a command line tool as it usually doesn't hang around, makes a request and exits.

But either case aside IMO it's best to avoid needless abstraction on a "might need this" basis, especially one as simple to implement later as this.

[the remark this answers is not in the document]
Comment (bebehei) [reply src/queues.c]: I agree with you IMO, but I'm already working on #445 and to have the ability for a signal is mandatory for #216.

Also the status field is declared static in dunst.c.

File: test/queues.h [hunk 10]
```diff
@@ -0,0 +1,57 @@
...
+#define QUEUE_CONTAINSm(msg, q, n) ASSERTm(msg, g_queue_find(QUEUE(q), n))
+
+#define NOT_LAST(n) do {ASSERT_EQm("Notification " #n " should have been deleted.", 1, notification_refcount_get(n)); g_clear_pointer(&n, notification_unref); } while(0)
+
+static inline struct notification *test_notification(const char *name, gint64 timeout)
+{
+        struct notification *n = notification_create();
+
+        if (timeout != -1)
+                n->timeout = S2US(timeout);
```
Comment (tsipinakis) [inline test/queues.h]: Huh, here's a case I didn't consider: What if timeout is `-1`? It will be multiplied anyway and there are some places in the code we explicitly check for `-1` like [`rules.c`](https://github.com/dunst-project/dunst/blob/master/src/rules.c#L17), need to check if there are breakages with this.

File: test/queues.h [hunk 11]
```diff
@@ -0,0 +1,57 @@
...
+        } while (0)
+
+#define QUEUE_IS(q, exp) QUEUE_ISm("QUEUE_IS(" #q "," #exp ")", q, exp)
+#define QUEUE_ISm(msg, q, exp) ASSERTm(msg, (exp == QUEUE(q)))
+#define QUEUE_CONTAINS(q, n) QUEUE_CONTAINSm("QUEUE_CONTAINS(" #q "," #n ")", q, n)
+#define QUEUE_CONTAINSm(msg, q, n) ASSERTm(msg, g_queue_find(QUEUE(q), n))
+
+#define NOT_LAST(n) do {ASSERT_EQm("Notification " #n " should have been deleted.", 1, notification_refcount_get(n)); g_clear_pointer(&n, notification_unref); } while(0)
+
+static inline struct notification *test_notification(const char *name, gint64 timeout)
```
Comment (tsipinakis) [inline test/queues.h]: What's the point of the `timeout` parameter? In the test cases you change the field you are testing on the next instruction, why have a parameter that's `-1` most of the time?

File: src/dunst.c [hunk 12]
```diff
@@ -24,6 +25,34 @@
 
 GMainLoop *mainloop = NULL;
 
+static struct dunst_status status;
+
+/* see dunst.h */
+void dunst_status(const enum dunst_status_field field,
+                  bool value)
```
Comment (tsipinakis) [inline src/dunst.c]: `value` can also be `const`, but is there a point declaring variables on the stack as `const`?

File: test/queues.h (hunk 10 above)
Comment (bebehei) [reply test/queues.h]: `-1` is the default for the notification's timeout:

https://github.com/dunst-project/dunst/blob/d786381cb0d52788de56732fe0f781e4823b6e99/src/notification.c#L312

A timeout of `-1` doesn't interfere with rules at all.

Also in `notification_init` every timeout below 0 will become the default timeout.

https://github.com/dunst-project/dunst/blob/d786381cb0d52788de56732fe0f781e4823b6e99/src/notification.c#L340-L342

File: test/queues.h (hunk 11 above)
Comment (bebehei) [reply test/queues.h]: ?

File: src/dunst.c (hunk 12 above)
Comment (bebehei) [reply src/dunst.c]: "Just because I can":tm:

Actually there is no specific reason. I started doing it with strings (where it's a useful thing).

But yes, either both params should be `const` or not.

File: test/queues.h (hunk 11 above)
Comment (tsipinakis) [reply test/queues.h]: Nevermind, I took a look at the first few test commits and noticed that `timeout` was `-1` for all of them and assumed it was a redundant parameter. A quick `grep` told me it's actually used more often.

File: test/queues.c [hunk 13]
```diff
@@ -166,8 +166,116 @@ TEST test_queue_teardown(void)
...
+
+        struct notification *n = test_notification("n", 10);
+
+        queues_notification_insert(n);
+        ASSERTm("The inserted notification is inside the waiting queue, so it should get ignored.",
+               queues_get_next_datachange(time_monotonic_now()) < S2US(0));
+
+        queues_update(STATUS_NORMAL);
+        ASSERT_IN_RANGEm("The notification has to get closed in less than its timeout",
+               S2US(10), queues_get_next_datachange(time_monotonic_now()), S2US(10));
```
Comment (tsipinakis) [inline test/queues.c]: `ASSERT_IN_RANGE` doesn't make sense here, for one it assumes the value is double which makes the error message confusing by using scientific notation and secondly if `S2US(15)` is returned it still passes as it checks for `+/- S2US(10)`.

File: test/queues.c [hunk 14]
```diff
@@ -166,8 +166,116 @@ TEST test_queue_teardown(void)
...
+        queues_update(STATUS_NORMAL);
+        ASSERT_IN_RANGEm("The notification has to get closed in less than its timeout.",
+               S2US(n->timeout), queues_get_next_datachange(time_monotonic_now()), S2US(n->timeout));
+
+        n = test_notification("n2", 10);
+
+        queues_notification_insert(n);
+        queues_update(STATUS_NORMAL);
+        ASSERT_IN_RANGEm("The timeout of the second notification has to get used as sleep time now.",
+               S2US(n->timeout), queues_get_next_datachange(time_monotonic_now()), S2US(n->timeout));
```
Comment (tsipinakis) [inline test/queues.c]: Same thing in this test.

File: test/queues.c [hunk 15]
```diff
@@ -2,6 +2,36 @@
...
+        queues_notification_close(n, REASON_UNDEF);
+
+        n = test_notification("n2", 0);
+        queues_notification_insert(n);
+        queues_update(STATUS_NORMAL);
+
+        n = test_notification("n3", 0);
+        queues_notification_insert(n);
+
+        QUEUE_LEN_ALL(1,1,1);
```
Comment (tsipinakis) [inline test/queues.c]: It'd be a good idea to also check as you're adding the notifications to ensure that they're being put in the correct queue rather than only at the end.

File: test/queues.c [hunk 16]
```diff
@@ -2,6 +2,36 @@
...
+
+        ASSERT_EQm("Queue waiting has to contain an element",
+                   1, queues_length_waiting());
+        ASSERT_EQm("Queue displayed has to contain an element",
+                   1, queues_length_displayed());
+        ASSERT_EQm("Queue history has to contain an element",
+                   1, queues_length_history());
```
Comment (tsipinakis) [inline test/queues.c]: These are redundant: if `QUEUE_LEN_ALL` fails above they won't get run either way, if it succeeds they will pass.

Comment (bebehei) [reply test/queues.c]: I already wanted to rebase and remove it. The test seems duplicated.

Bit it isn't: The test wants to test `queues_length_*`, so we have those `ASSERT_EQm`.

File: test/queues.c (hunk 15 above)
Comment (bebehei) [reply test/queues.c]: It's not important which notification is where. It's just an assertion, that every queue will contain an element.

And it seems to be redundant, but think about it like an assertion. If the `queues_notification_insert` and `queues_update` will fail, the test doesn't step into the problem, that `queues_length_*` reports the wrong size.

File: test/queues.c (hunk 14 above)
Comment (bebehei) [reply test/queues.c]: There's something worse. Do you spot the problem?

File: test/queues.c (hunk 13 above)
Comment (bebehei) [reply test/queues.c]: Oh, well it **does** make sense. Most importantly it has to be less than the actual timeout. But also it should be non-negative (this would be the representation for not sleeping).

File: test/queues.c (hunk 14 above)
Comment (tsipinakis) [reply test/queues.c]: Oh, calling `S2US` on `timeout` nice catch!

**Comment by tsipinakis** [comment]
Heads up: I pushed a fixup for a small bug in my id assignment commit.

**Comment by bebehei** [comment]
> Heads up: I pushed a fixup for a small bug in my id assignment commit.

Thoughts in order:

1. Yay, thanks! 
1. Wait, all your comments which got automatically marked outdated, aren't outdated anymore!?
1. Surprise surprise, all my changes are gone! :tada: 

I'm glad that I'm a GitHub beta member (you can click on the images to see the diff):

[Force Push IMG](https://github.com/dunst-project/dunst/compare/c646aeced84a14e016a92b3e562214fe96ea362a..69aa7c4fa942adba807cdb4ea5423f2966804297)

[Force push tsipinakis](https://github.com/dunst-project/dunst/compare/69aa7c4fa942adba807cdb4ea5423f2966804297..811090d77a99efbd62acb1b19e12fee602c5306e)

Please fetch the upstream pull request the next time first. If you need to fetch them very easily, there's a simple refspec available to fetch the GitHub PRs automatically: https://bebehei.de/github-prs/

**Comment by tsipinakis** [comment]
> Surprise surprise, all my changes are gone! tada

Oh crap, sorry! totally forgot you had pushed more changes in the meantime!

**Comment by bebehei** [comment]
Well, this happens.

Would you mind giving a final review?

File: test/queues.c [hunk 17]
```diff
@@ -364,6 +364,65 @@ TEST test_datachange_ttl(void)
...
+TEST test_queue_stacktag(void)
+{
+        const char *stacktag = "THIS IS A SUPER WIERD STACK TAG";
+        struct notification *n1, *n2, *n3;
+
+        queues_init();
+
+        n1 = test_notification("n1", 1);
+        n2 = test_notification("n2", 1);
+        n3 = test_notification("n3", 1);
```
Comment (tsipinakis) [inline test/queues.c]: Looking at this again the timeout parameter _does_ seem redundant. What's the point in setting it to `1` here? Any value wouldn't make a difference as we aren't advancing time.

But anyway, that's a complete nitpick everything else looks good.

Comment (bebehei) [reply test/queues.c]: I guess this is a typo introduced via vim block mode during refactoring.
